name: News Bot NASDAQ GOLD

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install requirements
        run: pip install requests

      - name: Run bot
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: python main.py
